spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.11.100/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true


# 服务器根节点
#server:
##  context-path: /sell
#  port: 80

wechat:
  mpAppid: wxc0088e8c934f4f4c
  mpAppsecret: 2f263b695ca15b181cf7a9b7b65ecccc
  callback: http://fzh.nat300.top/wechat/callback
projectUrl:
  wechatMpAuthorize: http://fzh.nat300.top
  wechatOpenAuthorize: http://fzh.nat300.top
  sell: http://fzh.nat300.top

