spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.11.100/sell?characterEncoding=utf-8&useSSL=false

  jpa:
    show-sql: true

# 服务器根节点
server:
  context-path: /sell
